<AutoFileChooser>
    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            size_hint_y: None
            height: sp(52)

            Button:
                text: 'Icon View'
                on_press: fc.view_mode = 'icon'
            Button:
                text: 'List View'
                on_press: fc.view_mode = 'list'
            Button:
                text: 'choose'
                on_press: root.filepath = fc.path

        FileChooser:
            id: fc
            font_name: "Droid-Sans-Fallback-Regular-2"
            FileChooserIconLayout
            FileChooserListLayout

<TriggerAutoMission>
    BoxLayout:
        orientation: 'vertical'    

        BoxLayout:

            size_hint_y: None
            height: sp(52)
            TextInput:
                font_name: "Droid-Sans-Fallback-Regular-2"
                id: inputfilepath
                text: 'Input File Path'

        BoxLayout:
            size_hint_y: None
            height: sp(52)

            TextInput:
                font_name: "Droid-Sans-Fallback-Regular-2"
                id: outputfilepath
                text: 'output File Path'

        BoxLayout:
            size_hint_y: None
            height: sp(52)

            TextInput:
                font_name: "Droid-Sans-Fallback-Regular-2"
                id: options
                text: 'Options'

        BoxLayout:
            size_hint_y: None
            height: sp(52)
            orientation: 'vertical'

            Button:
                font_name: "Droid-Sans-Fallback-Regular-2"
                text: "Run!"
                on_press: root.startTriggerAuto()

        BoxLayout:
            size_hint_y: None
            height: sp(52)

            Label:
                font_name: "Droid-Sans-Fallback-Regular-2"
                text: "stdout"

            Label:
                font_name: "Droid-Sans-Fallback-Regular-2"
                text: "stderr"

        BoxLayout:
            size_hint_y: root.height
            height: sp(52)

            ScrollView:
                Label:
                    font_name: "Droid-Sans-Fallback-Regular-2"
                    id: stdout
                    text_size: self.width, self.height
                    halign: 'left'
                    valign: 'top'
                
            ScrollView:
                Label:
                    font_name: "Droid-Sans-Fallback-Regular-2"
                    id: stderr     
                    text_size: self.width, self.height
                    halign: 'left'
                    valign: 'top'

