# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: get python requirement
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: set conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: "RustedWarfare"
        channels: conda-forge,defaults
    - name: create environment of conda
      run: |
        conda install pipreqs
        pipreqs -v
    - name: create requirement.txt
      run: |
        pipreqs . --force
